# pubspec.yaml
name: forge_cards_web
description: Forge cards (Flutter Web microapp)
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # ⬇️ Add this block
  assets:
    # Card background texture used by the front card
    - assets/plain_card_textures/texture_6.png
    - assets/backgrounds/background_1.png
    - assets/qr_designs/qr_design_5.png

    # Your per-card image galleries (folders are allowed; all files inside get bundled)
